#!/bin/sh

VERSION=5.6.21
BASEDIR=$PWD
BUILDDIR=$BASEDIR/build
ROOTDIR=$BASEDIR/install
SRCDIR=$BASEDIR/mysql-$VERSION

if [ ! -f mysql-$VERSION.tar.gz ]; then
    wget http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-$VERSION.tar.gz
fi
tar zxf mysql-$VERSION.tar.gz


mkdir -p $BUILDDIR
mkdir -p $ROOTDIR/etc

cd $SRCDIR
patch -p1 < ../osv.patch

cd $BUILDDIR
CFLAGS="-fPIC" CXXFLAGS="-fPIC" cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release ../mysql-$VERSION
make -j`nproc`
make install DESTDIR=$ROOTDIR

cd $ROOTDIR
egrep mysql /etc/services > etc/services
cp $BASEDIR/my.cnf etc/
rm usr/my.cnf
cd usr

rm -r data
./scripts/mysql_install_db --force --basedir=./ --ldata=data
cat <<EOF | eval './bin/mysqld  --bootstrap --skip-grant-tables --basedir=./ --datadir=data --max_allowed_packet=8M --net_buffer_length=16K'
use mysql;
set default_storage_engine=MyISAM;
select * from mysql.user;
insert into user values('%', 'admin', password('osv'), 'Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','','','','',0,0,0,0,'mysql_native_password','','N');
delete from mysql.user where User = '' and Host = 'localhost';
EOF

cd $BASEDIR
./prepare_tpcc.sh

cd $BUILDDIR/sql
$(cat CMakeFiles/mysqld.dir/link.txt) -shared
cd $BASEDIR

echo "
/etc/**: ${ROOTDIR}/etc/**
/usr/share/**: ${ROOTDIR}/usr/share/**
/usr/lib/**: ${ROOTDIR}/usr/lib/**
/usr/data/**: ${ROOTDIR}/usr/data/**
/usr/bin/mysqld: ${BUILDDIR}/sql/mysqld
" > usr.manifest
